/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.admin;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import view.SingInFrame;

/**
 *
 * @author rpbp
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJDialog
     */
    public MenuFrame(SingInFrame parent, boolean modal) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                System.exit(0);
            }
        });
        Image icono = new ImageIcon(getClass().getResource("/assets/icon.png")).getImage();
        setIconImage(icono);
        setResizable(false);
        setTitle("Menú");
        getContentPane().setBackground(new Color(255, 228, 235));
        this.usuarioProfesionalesButton.setBackground(new Color(255, 255, 255));
        this.usuariosPersonalesButton.setBackground(new Color(255, 255, 255));
    }

    public MenuFrame(UserProfessionalManagerDialog view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                System.exit(0);
            }
        });
        Image icono = new ImageIcon(getClass().getResource("/assets/icon.png")).getImage();
        setIconImage(icono);
        setResizable(false);
        setTitle("Menú");
        getContentPane().setBackground(new Color(255, 228, 235));
        this.usuarioProfesionalesButton.setBackground(new Color(255, 255, 255));
        this.usuariosPersonalesButton.setBackground(new Color(255, 255, 255));
    }

    public MenuFrame(UserPersonalManagerDialog view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                System.exit(0);
            }
        });
        Image icono = new ImageIcon(getClass().getResource("/assets/icon.png")).getImage();
        setIconImage(icono);
        setResizable(false);
        setTitle("Menú");
        getContentPane().setBackground(new Color(255, 228, 235));
        this.usuarioProfesionalesButton.setBackground(new Color(255, 255, 255));
        this.usuariosPersonalesButton.setBackground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        registerLabel1 = new javax.swing.JLabel();
        usuarioProfesionalesButton = new javax.swing.JButton();
        usuariosPersonalesButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        cerrarSesionMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));

        registerLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        registerLabel1.setText("Menú");

        usuarioProfesionalesButton.setText("UsuarioProfesionales");

        usuariosPersonalesButton.setText("UsuariosPersonales");

        userLabel.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText(" ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Escalada.png"))); // NOI18N

        fileMenu.setText("File");

        cerrarSesionMenuItem.setText("Cerrar Sesión");
        fileMenu.add(cerrarSesionMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(usuarioProfesionalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(usuariosPersonalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(registerLabel1)
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioProfesionalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuariosPersonalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Añadir acción a los botones y menuItems.
    public void addUsuarioProfesionalButtonActionListener(ActionListener al) {
        this.usuarioProfesionalesButton.addActionListener(al);
    }

    public void addUsuarioPersonalButtonActionListener(ActionListener al) {
        this.usuariosPersonalesButton.addActionListener(al);
    }

    public void addCerrarSesionMenuItem(ActionListener al) {
        this.cerrarSesionMenuItem.addActionListener(al);
    }

    public void addQuitMenuItem(ActionListener al) {
        this.quitMenuItem.addActionListener(al);
    }
    
    //Cambiar texto del label.
    public void setUserLabel(String user) {
        this.userLabel.setText(user);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesionMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JLabel registerLabel1;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton usuarioProfesionalesButton;
    private javax.swing.JButton usuariosPersonalesButton;
    // End of variables declaration//GEN-END:variables
}
