/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.Personal;

import java.awt.event.ActionListener;
import view.CentroManagerDialog;
import view.DatosPersonalDialog;
import view.InicioSesionDialog;
import view.TareasManagerPersonalDialog;
import view.UserManageJDialog;

/**
 *
 * @author rpbp
 */
public class MenuDialogPersonal extends javax.swing.JDialog {

    /**
     * Creates new form MenuJDialog
     */
    public MenuDialogPersonal(InicioSesionDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public MenuDialogPersonal(UserManageJDialog view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MenuDialogPersonal(DatosPersonalDialog view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MenuDialogPersonal(CentroManagerDialog view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MenuDialogPersonal(TareasManagerPersonalDialog view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        registerLabel1 = new javax.swing.JLabel();
        centrosButton = new javax.swing.JButton();
        tareasButton = new javax.swing.JButton();
        datosCuentaButton = new javax.swing.JButton();
        chatButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        cerrarSesionMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));

        registerLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        registerLabel1.setText("Menú");

        centrosButton.setText("Centros");

        tareasButton.setText("Tareas");

        datosCuentaButton.setText("Cuenta");

        chatButton.setText("Chat");
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText(" ");

        fileMenu.setText("File");

        cerrarSesionMenuItem.setText("Cerrar Sesión");
        fileMenu.add(cerrarSesionMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tareasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(centrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(datosCuentaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 177, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerLabel1)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(userLabel)
                .addGap(18, 18, 18)
                .addComponent(registerLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosCuentaButton)
                    .addComponent(tareasButton))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatButton)
                    .addComponent(centrosButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatButtonActionPerformed
    public void addCerrarSesionMenuItem(ActionListener al) {
        this.cerrarSesionMenuItem.addActionListener(al);
    }

    public void addQuitMenuItem(ActionListener al) {
        this.quitMenuItem.addActionListener(al);
    }

    public void setUserLabel(String user) {
        this.userLabel.setText(user);
    }

    public void addTareasButtonActionListener(ActionListener al) {
        this.tareasButton.addActionListener(al);
    }

    public void addDatosButtonActionListener(ActionListener al) {
        this.datosCuentaButton.addActionListener(al);
    }

    public void addCentrosButtonActionListener(ActionListener al) {
        this.centrosButton.addActionListener(al);
    }

    public void addChatButtonActionListener(ActionListener al) {
        this.chatButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton centrosButton;
    private javax.swing.JMenuItem cerrarSesionMenuItem;
    private javax.swing.JButton chatButton;
    private javax.swing.JButton datosCuentaButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JLabel registerLabel1;
    private javax.swing.JButton tareasButton;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
