/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.main;

import view.profesional.RegistroFrameProfessional;
import java.awt.Color;
import java.awt.Image;
import view.personal.PersonalSingUpFrame;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;
import view.SingInFrame;

/**
 *
 * @author rpbp
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Image icono = new ImageIcon(getClass().getResource("/assets/icon.png")).getImage();
        setIconImage(icono);
        setResizable(false);
        setTitle("Abuelitas");
        getContentPane().setBackground(new Color(255, 228, 235));
        this.singInButton.setBackground(new Color(255, 255, 255));
        this.singUpButton.setBackground(new Color(255, 255, 255));
    }

    public MainJFrame(SingInFrame view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
        Image icono = new ImageIcon(getClass().getResource("/assets/icon.png")).getImage();
        setIconImage(icono);
        setResizable(false);
        setTitle("Abuelitas");
        getContentPane().setBackground(new Color(255, 228, 235));
        this.singInButton.setBackground(new Color(255, 255, 255));
        this.singUpButton.setBackground(new Color(255, 255, 255));
    }

    public MainJFrame(RegistroFrameProfessional view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
        Image icono = new ImageIcon(getClass().getResource("/assets/icon.png")).getImage();
        setIconImage(icono);
        setResizable(false);
         setTitle("Abuelitas");
        getContentPane().setBackground(new Color(255, 228, 235));
        this.singInButton.setBackground(new Color(255, 255, 255));
        this.singUpButton.setBackground(new Color(255, 255, 255));
    }

    public MainJFrame(PersonalSingUpFrame view, boolean b) {
        initComponents();
        setLocationRelativeTo(null);
        Image icono = new ImageIcon(getClass().getResource("/assets/icon.png")).getImage();
        setIconImage(icono);
        setResizable(false);
         setTitle("Abuelitas");
        getContentPane().setBackground(new Color(255, 228, 235));
        this.singInButton.setBackground(new Color(255, 255, 255));
        this.singUpButton.setBackground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Metodo para añadir acción a los botones y al menuItem
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        singInButton = new javax.swing.JButton();
        singUpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        singInButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        singInButton.setText("Iniciar sesión");

        singUpButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        singUpButton.setText("Registrarse");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Grande.png"))); // NOI18N

        fileMenu.setText("File");

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(singInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(singUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addSingInButtonActionListener(ActionListener al) {
        this.singInButton.addActionListener(al);
    }

    public void addSingUpButtonActionListener(ActionListener al) {
        this.singUpButton.addActionListener(al);
    }

    public void addQuitMenuItem(ActionListener al) {
        this.quitMenuItem.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JButton singInButton;
    private javax.swing.JButton singUpButton;
    // End of variables declaration//GEN-END:variables
}
